language: node_js
node_js: stable
branches:
  only:
  - master
install:
- npm install
script:
- npm run build:example
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
