version: '3'
services:
  ytui: #项目的 service name
    container_name: 'ytui-container' #容器名称
    image: nginx #指定镜像
    ports:
      - 8081:80
    volumes:
      #~ ./dist 为宿主机 build 后的 dist 目录, /usr/share/nginx/html 为容器目录,
      - ./dist:/usr/share/nginx/html #挂载项目
